### ISSUE TITLE
关于feign.hystrix.enabled=false的疑问

### ISSUE THREAD

**Issue by juneryo** [codingapi/springcloud-lcn-demo#1]
虽然说融断、降级这个东西在某些情况下是会和分布式事物有些矛盾。。。
但是直接就把这个给禁用了，是不是有些不合适呢？
调用某些查询类的服务，也用不到分布式事物呢。

另外，tx-manager会不会考虑直接提供docker镜像呢？

**Comment by 1991wangliang** [comment]
feign.hystrix.enabled=false 不是每个demo都禁用的，在mybatis的demo下是开启的，可以参看mybatis的demo使用。

**Comment by juneryo** [comment]
了解了。。。刚才确实只看了jpa的demo。。。
