### ISSUE TITLE
现在还需要设置信号量模式吗？

### ISSUE THREAD

**Issue by beliefstar** [codingapi/springcloud-lcn-demo#4]
本地不设置信号量模式，事务也正常，这个已经被修复了吗？

**Comment by aywangchen** [comment]
@zhenxin77520 您好，最近在使用的过程中也发现了这个问题，熔断器默认是线程隔离的，在使用的过程中没有问题，groupId等参数依旧可以拿到，v4.1版本中增加了一个TransactionRestTemplateInterceptor拦截器，在拦截器中将groupId放入到了request header中,难道这就解决了多线程的问题了？
